version: '2'
services:
    user-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/user/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
